server:
  port: ${SERVER_PORT:8090}
  shutdown: graceful
  undertow:
    threads:
      io: ${UNDERTOW_IO_THREADS:10}
      worker: ${UNDERTOW_IO_WORKERS:100}
  servlet:
    context-path: /api

spring:
  application:
    name: mc-games
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

aws:
  region: "us-east-1"
  accessKey: "accessK3y"
  secretKey: "secretK3y"
  dynamodb:
    endpoint: "http://localhost:4569"

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
  pattern:
    console: "[%thread][%highlight(%-5level)][%cyan(%d{yyyy-MM-dd HH:mm:ss})][%yellow(%X{requestId})][%magenta(%logger{40})] - %msg%n"